In [16]:
# print misclassified model rows from dataset

import pandas as pd
from IPython.display import display

df = pd.read_excel("updated_output.xlsx")

cols = ['Products ID', 'Name', 'Castrads SKU', 'Family', 'Manufacturer', 'Tags',
       'Section Length (mm)', 'Leg Section Depth (mm)',
       'Mid Section Depth (mm)', 'Leg Section Height (mm)',
       'Mid Section Height (mm)', 'Leg Section Weight (kg)',
       'Mid Section Weight (kg)', 'Internal Volume (L)', 'Nipple Size Top (")',
       'Nipple Size Bottom (")', 'Pipe Centre Top To Floor (mm)',
       'Pipe Centre Bottom To Floor (mm)', 'Inter Axis Distance (mm)',
       'Exponent N', 'Factor Km', 'Output Dt50 (W)', 'Cross-brace type',
       'Top shape', 'Link to google drive image', 'DOP No.', 'Comments']

pd.set_option("display.max_colwidth", None) 
pd.set_option("display.max_columns", None)


display(df[df["Products ID"] == 11489][cols])


display(df[df["Products ID"] == 1207][cols])

,Products ID,Name,Castrads SKU,Family,Manufacturer,Tags,Section Length (mm),Leg Section Depth (mm),Mid Section Depth (mm),Leg Section Height (mm),Mid Section Height (mm),Leg Section Weight (kg),Mid Section Weight (kg),Internal Volume (L),"Nipple Size Top ("")","Nipple Size Bottom ("")",Pipe Centre Top To Floor (mm),Pipe Centre Bottom To Floor (mm),Inter Axis Distance (mm),Exponent N,Factor Km,Output Dt50 (W),Cross-brace type,Top shape,Link to google drive image,DOP No.,Comments
113,11489,American Radiator Company Perfection 2 Column 23in,ORC-ARC-PF-2C23,Perfection,American Radiator Company,"ARC, National,Ornate Radiators, Ribbon, 2 Column",64,235,184,584,533,7.5,6.8,1.9,2.0,2.0,535.0,114,421.0,1.25,0.69,92.0,NaN,Scrolled,NaN,202604-1114,NaN

,Products ID,Name,Castrads SKU,Family,Manufacturer,Tags,Section Length (mm),Leg Section Depth (mm),Mid Section Depth (mm),Leg Section Height (mm),Mid Section Height (mm),Leg Section Weight (kg),Mid Section Weight (kg),Internal Volume (L),"Nipple Size Top ("")","Nipple Size Bottom ("")",Pipe Centre Top To Floor (mm),Pipe Centre Bottom To Floor (mm),Inter Axis Distance (mm),Exponent N,Factor Km,Output Dt50 (W),Cross-brace type,Top shape,Link to google drive image,DOP No.,Comments
79,1207,American Radiator Company National 2 Column 23in,ORC-ARC-N-2C23,National,American Radiator Company,"ARC, National,Ornate, Ribbon, 2 Column",64,216,187,584,533,7.5,6.8,1.9,2.0,2.0,535.0,114,421.0,1.25,0.69,92.0,NaN,Scrolled,https://drive.google.com/file/d/14TKw751Q-i0s1_3inkmc8ckZFBepN9Om/view?usp=sharing,202604-1080,NaN

Observable difference: "Leg section depth" and "mid section depth" threshold difference

In [17]:
display(df[df["Products ID"] == 10658][cols])
display(df[df["Products ID"] == 1042][cols])

,Products ID,Name,Castrads SKU,Family,Manufacturer,Tags,Section Length (mm),Leg Section Depth (mm),Mid Section Depth (mm),Leg Section Height (mm),Mid Section Height (mm),Leg Section Weight (kg),Mid Section Weight (kg),Internal Volume (L),"Nipple Size Top ("")","Nipple Size Bottom ("")",Pipe Centre Top To Floor (mm),Pipe Centre Bottom To Floor (mm),Inter Axis Distance (mm),Exponent N,Factor Km,Output Dt50 (W),Cross-brace type,Top shape,Link to google drive image,DOP No.,Comments
207,10658,Beeston Duchess Scroll 1 Column 24in,ORC-B-DS24,Duchess,Beeston,"Duchess, School, Ideal Plain, School, Scroll",76,143,121,610,559,6.5,6.1,1.0,2.0,2.0,565.0,102,463.0,1.25,0.53,70.0,unknown,Scrolled,NaN,202604-1208,NaN

,Products ID,Name,Castrads SKU,Family,Manufacturer,Tags,Section Length (mm),Leg Section Depth (mm),Mid Section Depth (mm),Leg Section Height (mm),Mid Section Height (mm),Leg Section Weight (kg),Mid Section Weight (kg),Internal Volume (L),"Nipple Size Top ("")","Nipple Size Bottom ("")",Pipe Centre Top To Floor (mm),Pipe Centre Bottom To Floor (mm),Inter Axis Distance (mm),Exponent N,Factor Km,Output Dt50 (W),Cross-brace type,Top shape,Link to google drive image,DOP No.,Comments
193,1042,Beeston Duchess 1 Column 24in,ORC-B-D24,Duchess,Beeston,"Duchess, School, Ideal Plain, School",76,143,121,610,559,6.5,6.1,1.0,2.0,2.0,565.0,102,463.0,1.25,0.53,70.0,NaN,Scrolled,https://drive.google.com/file/d/1BPH7x1r_yPNOqgzKzQDAJIz-NGEDYJxw/view?usp=sharing,202604-1194,NaN

Observable difference: different product id

In [9]:
display(df[df["Products ID"] == 10661][cols])
display(df[df["Products ID"] == 1045][cols])

,Products ID,Name,Castrads SKU,Family,Manufacturer,Tags,Section Length (mm),Leg Section Depth (mm),Mid Section Depth (mm),Leg Section Height (mm),Mid Section Height (mm),Leg Section Weight (kg),Mid Section Weight (kg),Internal Volume (L),"Nipple Size Top ("")","Nipple Size Bottom ("")",Pipe Centre Top To Floor (mm),Pipe Centre Bottom To Floor (mm),Inter Axis Distance (mm),Exponent N,Factor Km,Output Dt50 (W),Cross-brace type,Top shape,Link to google drive image,DOP No.,Comments
208,10661,Beeston Duchess Scroll 1 Column 30in,ORC-B-DS30,Duchess,Beeston,"Duchess, School, Ideal Plain, School, Scroll",76,143,121,762,711,8.0,7.2,1.2,2.0,2.0,718.0,102,616.0,1.25,0.67,89.0,NaN,Scrolled,NaN,202604-1209,NaN

,Products ID,Name,Castrads SKU,Family,Manufacturer,Tags,Section Length (mm),Leg Section Depth (mm),Mid Section Depth (mm),Leg Section Height (mm),Mid Section Height (mm),Leg Section Weight (kg),Mid Section Weight (kg),Internal Volume (L),"Nipple Size Top ("")","Nipple Size Bottom ("")",Pipe Centre Top To Floor (mm),Pipe Centre Bottom To Floor (mm),Inter Axis Distance (mm),Exponent N,Factor Km,Output Dt50 (W),Cross-brace type,Top shape,Link to google drive image,DOP No.,Comments
194,1045,Beeston Duchess 1 Column 30in,ORC-B-D30,Duchess,Beeston,"Duchess, School, Ideal Plain, School",76,143,121,762,711,8.0,7.2,1.2,2.0,2.0,718.0,102,616.0,1.25,0.67,89.0,NaN,Scrolled,https://drive.google.com/file/d/1PnU0N130V2F_rPEA7AXJdQbQGpMHnn7v/view?usp=sharing,202604-1195,NaN

Observable difference: different product id

In [10]:
display(df[df["Products ID"] == 10664][cols])
display(df[df["Products ID"] == 1048][cols])

,Products ID,Name,Castrads SKU,Family,Manufacturer,Tags,Section Length (mm),Leg Section Depth (mm),Mid Section Depth (mm),Leg Section Height (mm),Mid Section Height (mm),Leg Section Weight (kg),Mid Section Weight (kg),Internal Volume (L),"Nipple Size Top ("")","Nipple Size Bottom ("")",Pipe Centre Top To Floor (mm),Pipe Centre Bottom To Floor (mm),Inter Axis Distance (mm),Exponent N,Factor Km,Output Dt50 (W),Cross-brace type,Top shape,Link to google drive image,DOP No.,Comments
209,10664,Beeston Duchess Scroll 1 Column 36in,ORC-B-DS36,Duchess,Beeston,"Duchess, School, Ideal Plain, School, Scroll",76,143,121,914,864,8.6,7.7,1.4,2.0,2.0,870.0,102,768.0,1.25,0.82,109.0,NaN,Scrolled,NaN,202604-1210,NaN

,Products ID,Name,Castrads SKU,Family,Manufacturer,Tags,Section Length (mm),Leg Section Depth (mm),Mid Section Depth (mm),Leg Section Height (mm),Mid Section Height (mm),Leg Section Weight (kg),Mid Section Weight (kg),Internal Volume (L),"Nipple Size Top ("")","Nipple Size Bottom ("")",Pipe Centre Top To Floor (mm),Pipe Centre Bottom To Floor (mm),Inter Axis Distance (mm),Exponent N,Factor Km,Output Dt50 (W),Cross-brace type,Top shape,Link to google drive image,DOP No.,Comments
195,1048,Beeston Duchess 1 Column 36in,ORC-B-D36,Duchess,Beeston,"Duchess, School, Ideal Plain, School",76,143,121,914,864,8.6,7.7,1.4,2.0,2.0,870.0,102,768.0,1.25,0.82,109.0,NaN,Scrolled,NaN,202604-1196,NaN

Observable difference: different product id

In [11]:
display(df[df["Products ID"] == 10667][cols])
display(df[df["Products ID"] == 1051][cols])

,Products ID,Name,Castrads SKU,Family,Manufacturer,Tags,Section Length (mm),Leg Section Depth (mm),Mid Section Depth (mm),Leg Section Height (mm),Mid Section Height (mm),Leg Section Weight (kg),Mid Section Weight (kg),Internal Volume (L),"Nipple Size Top ("")","Nipple Size Bottom ("")",Pipe Centre Top To Floor (mm),Pipe Centre Bottom To Floor (mm),Inter Axis Distance (mm),Exponent N,Factor Km,Output Dt50 (W),Cross-brace type,Top shape,Link to google drive image,DOP No.,Comments
210,10667,Beeston Duchess Scroll 1 Column 39in,ORC-B-DS39,Duchess,Beeston,"Duchess, School, Ideal Plain, School, Scroll",76,143,140,991,933,9.1,8.2,1.5,2.0,2.0,943.0,102,841.0,1.25,0.89,118.0,NaN,Scrolled,NaN,202604-1211,NaN

,Products ID,Name,Castrads SKU,Family,Manufacturer,Tags,Section Length (mm),Leg Section Depth (mm),Mid Section Depth (mm),Leg Section Height (mm),Mid Section Height (mm),Leg Section Weight (kg),Mid Section Weight (kg),Internal Volume (L),"Nipple Size Top ("")","Nipple Size Bottom ("")",Pipe Centre Top To Floor (mm),Pipe Centre Bottom To Floor (mm),Inter Axis Distance (mm),Exponent N,Factor Km,Output Dt50 (W),Cross-brace type,Top shape,Link to google drive image,DOP No.,Comments
196,1051,Beeston Duchess 1 Column 39in,ORC-B-D39,Duchess,Beeston,"Duchess, School, Ideal Plain, School",76,143,121,991,933,9.1,8.2,1.5,2.0,2.0,943.0,102,841.0,1.25,0.89,118.0,NaN,Scrolled,NaN,202604-1197,NaN

Observable difference: "mid section depth" threshold difference

In [12]:
display(df[df["Products ID"] == 12704][cols])
display(df[df["Products ID"] == 12719][cols])

,Products ID,Name,Castrads SKU,Family,Manufacturer,Tags,Section Length (mm),Leg Section Depth (mm),Mid Section Depth (mm),Leg Section Height (mm),Mid Section Height (mm),Leg Section Weight (kg),Mid Section Weight (kg),Internal Volume (L),"Nipple Size Top ("")","Nipple Size Bottom ("")",Pipe Centre Top To Floor (mm),Pipe Centre Bottom To Floor (mm),Inter Axis Distance (mm),Exponent N,Factor Km,Output Dt50 (W),Cross-brace type,Top shape,Link to google drive image,DOP No.,Comments
233,12704,Beeston Hospital Wide 18in - 1957,ORC-B-H-W18,Beeston Hospital,Beeston,"Beeston, Hospital, School, Wide, Window",64,178,178,457,394,8.0,7.2,0.97,1.5,1.5,424.0,102,322.0,1.25,0.65,87.0,NaN,Curved,NaN,202604-1234,NaN

,Products ID,Name,Castrads SKU,Family,Manufacturer,Tags,Section Length (mm),Leg Section Depth (mm),Mid Section Depth (mm),Leg Section Height (mm),Mid Section Height (mm),Leg Section Weight (kg),Mid Section Weight (kg),Internal Volume (L),"Nipple Size Top ("")","Nipple Size Bottom ("")",Pipe Centre Top To Floor (mm),Pipe Centre Bottom To Floor (mm),Inter Axis Distance (mm),Exponent N,Factor Km,Output Dt50 (W),Cross-brace type,Top shape,Link to google drive image,DOP No.,Comments
232,12719,Beeston Hospital Wide 18in - 1914,ORC-B-H1914-W18,Beeston Hospital,Beeston,"Beeston, Hospital, School, Wide, Window",64,184,178,457,394,8.0,7.2,0.97,1.5,1.5,424.0,102,322.0,1.25,0.65,87.0,NaN,Curved,NaN,202604-1233,NaN

Observable difference: "leg section depth" threshold difference

In [13]:
display(df[df["Products ID"] == 10619][cols])
display(df[df["Products ID"] == 1006][cols])

,Products ID,Name,Castrads SKU,Family,Manufacturer,Tags,Section Length (mm),Leg Section Depth (mm),Mid Section Depth (mm),Leg Section Height (mm),Mid Section Height (mm),Leg Section Weight (kg),Mid Section Weight (kg),Internal Volume (L),"Nipple Size Top ("")","Nipple Size Bottom ("")",Pipe Centre Top To Floor (mm),Pipe Centre Bottom To Floor (mm),Inter Axis Distance (mm),Exponent N,Factor Km,Output Dt50 (W),Cross-brace type,Top shape,Link to google drive image,DOP No.,Comments
276,10619,Beeston Princess Scroll 1 Column 36in,ORC-B-PS36,Royal School,Beeston,"Princess, School, Ideal Plain, School, Scroll",76,143,121,914,864,8.6,7.7,1.4,2.0,2.0,870.0,102,768.0,1.25,0.82,109.0,NaN,Curved,NaN,202604-1277,NaN

,Products ID,Name,Castrads SKU,Family,Manufacturer,Tags,Section Length (mm),Leg Section Depth (mm),Mid Section Depth (mm),Leg Section Height (mm),Mid Section Height (mm),Leg Section Weight (kg),Mid Section Weight (kg),Internal Volume (L),"Nipple Size Top ("")","Nipple Size Bottom ("")",Pipe Centre Top To Floor (mm),Pipe Centre Bottom To Floor (mm),Inter Axis Distance (mm),Exponent N,Factor Km,Output Dt50 (W),Cross-brace type,Top shape,Link to google drive image,DOP No.,Comments
260,1006,Beeston Princess 1 Column 36in,ORC-B-P36,Princess,Beeston,"Princess, School, Ideal Plain, School",76,143,121,914,864,8.6,7.7,1.4,2.0,2.0,870.0,102,768.0,1.25,0.82,109.0,NaN,Curved,https://drive.google.com/file/d/1E1icNpjo4iimYKvB5X4mdmeZg3I8dQdl/view?usp=sharing,202604-1261,NaN

Observable difference: different family (princess vs royal school)

In [14]:
display(df[df["Products ID"] == 10649][cols])
display(df[df["Products ID"] == 1036][cols])

,Products ID,Name,Castrads SKU,Family,Manufacturer,Tags,Section Length (mm),Leg Section Depth (mm),Mid Section Depth (mm),Leg Section Height (mm),Mid Section Height (mm),Leg Section Weight (kg),Mid Section Weight (kg),Internal Volume (L),"Nipple Size Top ("")","Nipple Size Bottom ("")",Pipe Centre Top To Floor (mm),Pipe Centre Bottom To Floor (mm),Inter Axis Distance (mm),Exponent N,Factor Km,Output Dt50 (W),Cross-brace type,Top shape,Link to google drive image,DOP No.,Comments
286,10649,Beeston Princess Scroll 3 Column 36in,ORC-B-PS3C36,Royal School,Beeston,"Princess, School, Ideal Plain, School, 3 Column, Scroll",76,254,229,914,864,15.3,13.77,3.6,2.0,2.0,851.0,133,718.0,1.25,1.13,150.0,unknown,Curved,NaN,202604-1287,NaN

,Products ID,Name,Castrads SKU,Family,Manufacturer,Tags,Section Length (mm),Leg Section Depth (mm),Mid Section Depth (mm),Leg Section Height (mm),Mid Section Height (mm),Leg Section Weight (kg),Mid Section Weight (kg),Internal Volume (L),"Nipple Size Top ("")","Nipple Size Bottom ("")",Pipe Centre Top To Floor (mm),Pipe Centre Bottom To Floor (mm),Inter Axis Distance (mm),Exponent N,Factor Km,Output Dt50 (W),Cross-brace type,Top shape,Link to google drive image,DOP No.,Comments
270,1036,Beeston Princess 3 Column 36in,ORC-B-P3C36,Princess,Beeston,"Princess, School, Ideal Plain, School, 3 Column",76,254,229,914,838,15.3,13.77,3.6,2.0,2.0,851.0,133,718.0,1.25,1.13,150.0,NaN,Curved,https://drive.google.com/file/d/1lcH99E0ND6zmXY8K79ZXF8dVkhPgIL1Q/view?usp=sharing,202604-1271,NaN

Observable difference: different family (princess vs royal school)